--
-- This file was generated using: ./OpenBTS-UMTS --gensql
-- binary version: release 1.0-master P built 2014-10-16T13:56:05 2b46fbdc98 CommonLibs:2b46fbdc98 
--
-- Future changes should not be put in this file directly but
-- rather in the program's ConfigurationKey schema.
--
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS CONFIG ( KEYSTRING TEXT UNIQUE NOT NULL, VALUESTRING TEXT, STATIC INTEGER DEFAULT 0, OPTIONAL INTEGER DEFAULT 0, COMMENTS TEXT DEFAULT '');
INSERT OR IGNORE INTO "CONFIG" VALUES('CLI.SocketPath','/var/run/OpenBTS-UMTS-command',0,0,'Path for Unix domain datagram socket used for the OpenBTS-UMTS console interface.');
INSERT OR IGNORE INTO "CONFIG" VALUES('Control.LUR.AttachDetach','1',0,0,'1=enabled, 0=disabled - Use attach/detach procedure.  This will make initial LUR more prompt.  It will also cause an un-regstration if the handset powers off and really heavy LUR loads in areas with spotty coverage.');
INSERT OR IGNORE INTO "CONFIG" VALUES('Control.LUR.FailedRegistration.Message','Your handset is not provisioned for this network. ',0,0,'Send this text message, followed by the IMSI, to unprovisioned handsets that are denied registration.');
INSERT OR IGNORE INTO "CONFIG" VALUES('Control.LUR.FailedRegistration.ShortCode','1000',0,0,'The return address for the failed registration message.');
INSERT OR IGNORE INTO "CONFIG" VALUES('Control.LUR.NormalRegistration.Message','',0,0,'The text message (followed by the IMSI) to be sent to provisioned handsets when they attach on Um.  By default, no message is sent.  To have a message sent, specify one.  To stop sending messages again, execute "unconfig Control.LUR.NormalRegistration.Message".');
INSERT OR IGNORE INTO "CONFIG" VALUES('Control.LUR.NormalRegistration.ShortCode','0000',0,0,'The return address for the normal registration message.');
INSERT OR IGNORE INTO "CONFIG" VALUES('Control.LUR.OpenRegistration','',0,0,'This is value is a regular expression.  Any handset with an IMSI matching the regular expression is allowed to register, even if it is not provisioned.  By default, this feature is disabled.  To enable open registration, specify a regular expression e.g. ^460 (which matches any IMSI starting with 460, the MCC for China).  To disable open registration again, execute "unconfig Control.LUR.OpenRegistration".');
INSERT OR IGNORE INTO "CONFIG" VALUES('Control.LUR.OpenRegistration.Message','Welcome to the test network.  Your IMSI is ',0,0,'Send this text message, followed by the IMSI, to unprovisioned handsets when they attach on Um due to open registration.');
INSERT OR IGNORE INTO "CONFIG" VALUES('Control.LUR.OpenRegistration.ShortCode','101',0,0,'The return address for the open registration message.');
INSERT OR IGNORE INTO "CONFIG" VALUES('Control.LUR.QueryClassmark','0',0,0,'1=enabled, 0=disabled - Query every MS for classmark during LUR.');
INSERT OR IGNORE INTO "CONFIG" VALUES('Control.LUR.QueryIMEI','0',0,0,'1=enabled, 0=disabled - Query every MS for IMEI during LUR.');
INSERT OR IGNORE INTO "CONFIG" VALUES('Control.LUR.SendTMSIs','0',0,0,'1=enabled, 0=disabled - Send new TMSI assignments to handsets that are allowed to attach.');
INSERT OR IGNORE INTO "CONFIG" VALUES('Control.LUR.UnprovisionedRejectCause','0x04',0,0,'Reject cause for location updating failures for unprovisioned phones.  Reject causes come from GSM 04.08 10.5.3.6.  Reject cause 0x04, IMSI not in VLR, is usually the right one.');
INSERT OR IGNORE INTO "CONFIG" VALUES('Control.NumSQLTries','3',0,0,'Number of times to retry SQL queries before declaring a database access failure.');
INSERT OR IGNORE INTO "CONFIG" VALUES('Control.Reporting.TMSITable','/var/run/OpenBTS-UMTS-TMSITable.db',1,0,'File path for TMSITable database.  Static.');
INSERT OR IGNORE INTO "CONFIG" VALUES('Control.Reporting.TransactionTable','/var/run/OpenBTS-UMTS-TransactionTable.db',1,0,'File path for transaction table database.  Static.');
INSERT OR IGNORE INTO "CONFIG" VALUES('Control.VEA','0',0,0,'1=enabled, 0=disabled - Use very early assignment for speech call establishment.  See GSM 04.08 Section 7.3.2 for a detailed explanation of assignment types.  If VEA is selected, GSM.CellSelection.NECI should be set to 1.  See GSM 04.08 Sections 9.1.8 and 10.5.2.4 for an explanation of the NECI bit.  Note that some handset models exhibit bugs when VEA is used and these bugs may affect performance.');
INSERT OR IGNORE INTO "CONFIG" VALUES('GGSN.DNS','',1,0,'The list of DNS servers to be used by downstream clients.  By default, DNS servers are taken from the host system.  To override, specify a space-separated list of the DNS servers, in IP dotted notation, eg: 1.2.3.4 5.6.7.8.  To use the host system DNS servers again, execute "unconfig GGSN.DNS".  Static.');
INSERT OR IGNORE INTO "CONFIG" VALUES('GGSN.Firewall.Enable','1',1,0,'0=no firewall; 1=block MS attempted access to OpenBTS-UMTS or other MS; 2=block all private IP addresses.  Static.');
INSERT OR IGNORE INTO "CONFIG" VALUES('GGSN.IP.MaxPacketSize','1520',1,0,'Maximum size of an IP packet.  Should normally be 1520.  Static.');
INSERT OR IGNORE INTO "CONFIG" VALUES('GGSN.IP.ReuseTimeout','180',1,0,'How long IP addresses are reserved after a session ends.  Static.');
INSERT OR IGNORE INTO "CONFIG" VALUES('GGSN.IP.TossDuplicatePackets','0',1,0,'1=enabled, 0=disabled - Toss duplicate TCP/IP packets to prevent unnecessary traffic on the radio.  Static.');
INSERT OR IGNORE INTO "CONFIG" VALUES('GGSN.Logfile.Name','',1,0,'If specified, internet traffic is logged to this file e.g. ggsn.log  Static.');
INSERT OR IGNORE INTO "CONFIG" VALUES('GGSN.MS.IP.Base','192.168.99.1',1,0,'Base IP address assigned to MS.  Static.');
INSERT OR IGNORE INTO "CONFIG" VALUES('GGSN.MS.IP.MaxCount','254',1,0,'Number of IP addresses to use for MS.  Static.');
INSERT OR IGNORE INTO "CONFIG" VALUES('GGSN.MS.IP.Route','',1,0,'A route address to be used for downstream clients.  By default, OpenBTS-UMTS manufactures this value from the GGSN.MS.IP.Base assuming a 24 bit mask.  To override, specify a route address in the form xxx.xxx.xxx.xxx/yy.  The address must encompass all MS IP addresses.  To use the auto-generated value again, execute "unconfig GGSN.MS.IP.Route".  Static.');
INSERT OR IGNORE INTO "CONFIG" VALUES('GGSN.ShellScript','',0,0,'A shell script to be invoked when MS devices attach or create IP connections.  By default, this feature is disabled.  To enable, specify an absolute path to the script you wish to execute e.g. /usr/bin/ms-attach.sh.  To disable again, execute "unconfig GGSN.ShellScript".');
INSERT OR IGNORE INTO "CONFIG" VALUES('GGSN.TunName','sgsntun',1,0,'Tunnel device name for GGSN.  Static.');
INSERT OR IGNORE INTO "CONFIG" VALUES('GPRS.Multislot.Max.Downlink','1',0,0,'Maximum number of channels used for a single MS in downlink.');
INSERT OR IGNORE INTO "CONFIG" VALUES('GPRS.Multislot.Max.Uplink','1',0,0,'Maximum number of channels used for a single MS in uplink.');
INSERT OR IGNORE INTO "CONFIG" VALUES('GPRS.NMO','1',0,0,'Network Mode of Operation.  See GSM 03.60 Section 6.3.3.1 and 24.008 4.7.1.6.  Allowed values are 1, 2, 3 for modes I, II, III.  Mode II (2) is recommended.  Mode I implies combined routing updating procedures.');
INSERT OR IGNORE INTO "CONFIG" VALUES('GPRS.RAC','100',1,0,'GPRS Routing Area Code, advertised in the C0T0 beacon.  Static.');
INSERT OR IGNORE INTO "CONFIG" VALUES('GSM.CCCH.CCCH-CONF','1',1,0,'CCCH configuration type.  See GSM 10.5.2.11 for encoding.  Value of 1 means we are using a C-V beacon.  Any other value selects a C-IV beacon.  In C2.9 and earlier, the only allowed value is 1.  Static.');
INSERT OR IGNORE INTO "CONFIG" VALUES('GSM.CellSelection.CELL-RESELECT-HYSTERESIS','3',0,0,'Cell Reselection Hysteresis.  See GSM 04.08 10.5.2.4, Table 10.5.23 for encoding.  Encoding is $2N$ dB, values of $N$ are 0...7 for 0...14 dB.');
INSERT OR IGNORE INTO "CONFIG" VALUES('GSM.CellSelection.MS-TXPWR-MAX-CCH','0',0,0,'Cell selection parameters.  See GSM 04.08 10.5.2.4.');
INSERT OR IGNORE INTO "CONFIG" VALUES('GSM.CellSelection.NCCsPermitted','1',0,0,'NCCs Permitted.  An 8-bit mask of allowed NCCs.  Unless you are coordinating with another carrier, this should probably just select your own NCC.');
INSERT OR IGNORE INTO "CONFIG" VALUES('GSM.CellSelection.NECI','1',0,0,'NECI, New Establishment Causes.  This must be set to 1 if you want to support very early assignment (VEA).  It can be set to 1 even if you do not use VEA, so you might as well leave it as 1.  See GSM 04.08 10.5.2.4, Table 10.5.23 and 04.08 9.1.8, Table 9.9 and the Control.VEA parameter.');
INSERT OR IGNORE INTO "CONFIG" VALUES('GSM.CellSelection.RXLEV-ACCESS-MIN','0',0,0,'Cell selection parameters.  See GSM 04.08 10.5.2.4.');
INSERT OR IGNORE INTO "CONFIG" VALUES('GSM.Identity.BSIC.BCC','2',0,0,'GSM basestation color code; lower 3 bits of the BSIC.  BCC values in a multi-BTS network should be assigned so that BTS units with overlapping coverage do not share a BCC.  This value will also select the training sequence used for all slots on this unit.');
INSERT OR IGNORE INTO "CONFIG" VALUES('GSM.Identity.LAC','1000',0,0,'Location area code, 16 bits, values 0xFFxx are reserved.  For multi-BTS networks, assign a unique LAC to each BTS unit.  (That is not the normal procedure in conventional GSM networks, but is the correct procedure in OpenBTS-UMTS networks.)');
INSERT OR IGNORE INTO "CONFIG" VALUES('GSM.Identity.MCC','001',0,0,'Mobile country code; must be three digits.  Defined in ITU-T E.212. 001 for test networks.');
INSERT OR IGNORE INTO "CONFIG" VALUES('GSM.Identity.MNC','01',0,0,'Mobile network code, two or three digits.  Assigned by your national regulator. 01 for test networks.');
INSERT OR IGNORE INTO "CONFIG" VALUES('GSM.MaxSpeechLatency','2',0,0,'Maximum allowed speech buffering latency, in 20 millisecond frames.  If the jitter is larger than this delay, frames will be lost.');
INSERT OR IGNORE INTO "CONFIG" VALUES('GSM.RACH.AC','0x0400',0,0,'Access class flags.  This is the raw parameter sent on the BCCH.  See GSM 04.08 10.5.2.29 for encoding.  Set to 0 to allow full access.  Set to 0x0400 to indicate no support for emergency calls.');
INSERT OR IGNORE INTO "CONFIG" VALUES('GSM.RACH.MaxRetrans','1',0,0,'Maximum RACH retransmission attempts.  This is the raw parameter sent on the BCCH.  See GSM 04.08 10.5.2.29 for encoding.');
INSERT OR IGNORE INTO "CONFIG" VALUES('GSM.RACH.TxInteger','14',0,0,'Parameter to spread RACH busts over time.  This is the raw parameter sent on the BCCH.  See GSM 04.08 10.5.2.29 for encoding.');
INSERT OR IGNORE INTO "CONFIG" VALUES('GSM.RRLP.SEED.LATITUDE','37.777423',0,0,'Seed latitude in degrees.  -90 (south pole) .. +90 (north pole)');
INSERT OR IGNORE INTO "CONFIG" VALUES('GSM.RRLP.SEED.LONGITUDE','-122.39807',0,0,'Seed longitude in degrees.  -180 (west of greenwich) .. 180 (east)');
INSERT OR IGNORE INTO "CONFIG" VALUES('GSM.ShowCountry','0',0,0,'1=enabled, 0=disabled - Tell the phone to show the country name based on the MCC.');
INSERT OR IGNORE INTO "CONFIG" VALUES('GSM.Timer.T3113','10000',0,0,'Paging timer T3113 in milliseconds.  This is the timeout for a handset to respond to a paging request.  This should usually be the same as SIP.Timer.B in your VoIP network.');
INSERT OR IGNORE INTO "CONFIG" VALUES('GSM.Timer.T3212','0',0,0,'Registration timer T3212 period in minutes.  Should be a factor of 6.  Set to 0 to disable periodic registration.  Should be smaller than SIP registration period.');
INSERT OR IGNORE INTO "CONFIG" VALUES('Log.Alarms.Max','20',0,0,'Maximum number of alarms to remember inside the application.');
INSERT OR IGNORE INTO "CONFIG" VALUES('Log.File','',0,0,'Path to use for textfile based logging.  By default, this feature is disabled.  To enable, specify an absolute path to the file you wish to use, eg: /tmp/my-debug.log.  To disable again, execute "unconfig Log.File".');
INSERT OR IGNORE INTO "CONFIG" VALUES('Log.Level','NOTICE',0,0,'Default logging level when no other level is defined for a file.');
INSERT OR IGNORE INTO "CONFIG" VALUES('RTP.Range','98',1,0,'Range of RTP port pool.  Pool is RTP.Start to RTP.Range-1.  Static.');
INSERT OR IGNORE INTO "CONFIG" VALUES('RTP.Start','16484',1,0,'Base of RTP port pool.  Pool is RTP.Start to RTP.Range-1.  Static.');
INSERT OR IGNORE INTO "CONFIG" VALUES('SGSN.Debug','0',0,0,'1=enabled, 0=disabled - Add layer-3 messages to the GGSN.Logfile, if any.');
INSERT OR IGNORE INTO "CONFIG" VALUES('SGSN.Timer.ImplicitDetach','3480',0,0,'3GPP 24.008 11.2.2.  GPRS attached MS is implicitly detached in seconds.  Should be at least 240 seconds greater than SGSN.Timer.RAUpdate.');
INSERT OR IGNORE INTO "CONFIG" VALUES('SGSN.Timer.MS.Idle','600',0,0,'How long an MS is idle before the SGSN forgets TLLI specific information.');
INSERT OR IGNORE INTO "CONFIG" VALUES('SGSN.Timer.RAUpdate','3240',0,0,'Also known as T3312, 3GPP 24.008 4.7.2.2.  How often MS reports into the SGSN when it is idle, in seconds.  Setting to 0 or >12000 deactivates entirely, i.e., sets the timer to effective infinity.  Note: to prevent GPRS Routing Area Updates you must set both this and GSM.Timer.T3212 to 0.  ');
INSERT OR IGNORE INTO "CONFIG" VALUES('SGSN.Timer.Ready','44',0,0,'Also known as T3314, 3GPP 24.008 4.7.2.1.  Inactivity period required before MS may perform another routing area or cell update, in seconds.');
INSERT OR IGNORE INTO "CONFIG" VALUES('SIP.DTMF.RFC2833','1',0,0,'1=enabled, 0=disabled - Use RFC-2833 (RTP event signalling) for in-call DTMF.');
INSERT OR IGNORE INTO "CONFIG" VALUES('SIP.DTMF.RFC2833.PayloadType','101',0,0,'Payload type to use for RFC-2833 telephone event packets.');
INSERT OR IGNORE INTO "CONFIG" VALUES('SIP.DTMF.RFC2967','0',0,0,'1=enabled, 0=disabled - Use RFC-2967 (SIP INFO method) for in-call DTMF.');
INSERT OR IGNORE INTO "CONFIG" VALUES('SIP.Local.IP','127.0.0.1',1,0,'IP address of the OpenBTS-UMTS machine as seen by its proxies.  If these are all local, this can be localhost.  Static.');
INSERT OR IGNORE INTO "CONFIG" VALUES('SIP.Local.Port','5062',1,0,'IP port that OpenBTS-UMTS uses for its SIP interface.  Static.');
INSERT OR IGNORE INTO "CONFIG" VALUES('SIP.MaxForwards','70',0,0,'Maximum allowed number of referrals.');
INSERT OR IGNORE INTO "CONFIG" VALUES('SIP.Proxy.Registration','127.0.0.1:5064',0,0,'The hostname or IP address and port of the proxy to be used for registration and authentication.  This should normally be the subscriber registry SIP interface, not Asterisk.');
INSERT OR IGNORE INTO "CONFIG" VALUES('SIP.Proxy.SMS','127.0.0.1:5063',0,0,'The hostname or IP address and port of the proxy to be used for text messaging.  This is smqueue, for example.');
INSERT OR IGNORE INTO "CONFIG" VALUES('SIP.Proxy.Speech','127.0.0.1:5060',0,0,'The hostname or IP address and port of the proxy to be used for normal speech calls.  This is Asterisk, for example.');
INSERT OR IGNORE INTO "CONFIG" VALUES('SIP.RegistrationPeriod','90',0,0,'Registration period in minutes for MS SIP users.  Should be longer than GSM T3212.');
INSERT OR IGNORE INTO "CONFIG" VALUES('SIP.SMSC','smsc',0,0,'The SMSC handler in smqueue.  This is the entity that handles full 3GPP MIME-encapsulted TPDUs.  If not defined, use direct numeric addressing.  The value should be disabled with "unconfig SIP.SMSC" if SMS.MIMEType is "text/plain" or set to "smsc" if SMS.MIMEType is "application/vnd.3gpp".');
INSERT OR IGNORE INTO "CONFIG" VALUES('SIP.Timer.A','2000',0,0,'SIP timer A, the INVITE retry period, RFC-3261 Section 17.1.1.2, in milliseconds.');
INSERT OR IGNORE INTO "CONFIG" VALUES('SIP.Timer.B','10000',0,0,'INVITE transaction timeout in milliseconds.  This value should usually match GSM.Timer.T3113.');
INSERT OR IGNORE INTO "CONFIG" VALUES('SIP.Timer.E','500',0,0,'Non-INVITE initial request retransmit period in milliseconds.');
INSERT OR IGNORE INTO "CONFIG" VALUES('SIP.Timer.F','5000',0,0,'Non-INVITE initial request timeout in milliseconds.');
INSERT OR IGNORE INTO "CONFIG" VALUES('SIP.Timer.H','5000',0,0,'ACK timeout period in milliseconds.');
INSERT OR IGNORE INTO "CONFIG" VALUES('SMS.FakeSrcSMSC','0000',0,0,'Use this to fill in L4 SMSC address in SMS delivery.');
INSERT OR IGNORE INTO "CONFIG" VALUES('SMS.MIMEType','application/vnd.3gpp.sms',0,0,'This is the MIME Type that OpenBTS-UMTS will use for RFC-3428 SIP MESSAGE payloads.  Valid values are "application/vnd.3gpp.sms" and "text/plain".');
INSERT OR IGNORE INTO "CONFIG" VALUES('SubscriberRegistry.A3A8','/OpenBTS/comp128',0,0,'Path to the program that implements the A3/A8 algorithm.');
INSERT OR IGNORE INTO "CONFIG" VALUES('SubscriberRegistry.Port','5064',0,0,'Port used by the SIP Authentication Server. NOTE: In some older releases (pre-2.8.1) this is called SIP.myPort.');
INSERT OR IGNORE INTO "CONFIG" VALUES('SubscriberRegistry.UpstreamServer','',0,0,'URL of the subscriber registry HTTP interface on the upstream server.  By default, this feature is disabled.  To enable, specify a server URL eg: http://localhost/cgi/subreg.cgi.  To disable again, execute "unconfig SubscriberRegistry.UpstreamServer".');
INSERT OR IGNORE INTO "CONFIG" VALUES('SubscriberRegistry.db','/var/lib/asterisk/sqlite3dir/sqlite3.db',0,0,'The location of the sqlite3 database holding the subscriber registry.');
INSERT OR IGNORE INTO "CONFIG" VALUES('TRX.IP','127.0.0.1',1,0,'IP address of the transceiver application.  Static.');
INSERT OR IGNORE INTO "CONFIG" VALUES('TRX.Port','5700',1,0,'IP port of the transceiver application.  Static.');
INSERT OR IGNORE INTO "CONFIG" VALUES('TRX.RadioFrequencyOffset','128',1,0,'Fine-tuning adjustment for the transceiver master clock.  Roughly 170 Hz/step.  Set at the factory.  Do not adjust without proper calibration.  Static.');
INSERT OR IGNORE INTO "CONFIG" VALUES('TRX.TxAttenOffset','0',1,0,'Hardware-specific gain adjustment for transmitter, matched to the power amplifier, expessed as an attenuationi in dB.  Set at the factory.  Do not adjust without proper calibration.  Static.');
INSERT OR IGNORE INTO "CONFIG" VALUES('UMTS.AICH.AICH-PowerOffset','-10',0,0,'AICH power offset in dB.');
INSERT OR IGNORE INTO "CONFIG" VALUES('UMTS.Best.Effort.BytesPerSec','60000',0,0,'Target Physical Bit Rate in bytes/s for DCH channels, actual data rate is roughly one-third of this.');
INSERT OR IGNORE INTO "CONFIG" VALUES('UMTS.CN-DSI.CycleLengthCoeff','6',0,0,'Have no idea.');
INSERT OR IGNORE INTO "CONFIG" VALUES('UMTS.CellSelect.MaxAlloweddUL-TX-Power','33',0,0,'Maximum Allowed UE transmit power in dBm.');
INSERT OR IGNORE INTO "CONFIG" VALUES('UMTS.DPCHFrameOffset','0',0,0,'DPCH frame offset in chips.  Not used.');
INSERT OR IGNORE INTO "CONFIG" VALUES('UMTS.Debug.ASN','0',0,0,'1=enabled, 0=disabled - Enable debug printouts of ASN messages.');
INSERT OR IGNORE INTO "CONFIG" VALUES('UMTS.Debug.ASN.Beacon','1',0,0,'1=enabled, 0=disabled - Flag to print debugging ASN info about BCH messages.');
INSERT OR IGNORE INTO "CONFIG" VALUES('UMTS.Debug.ASN.Free','0',0,0,'1=enabled, 0=disabled - Have no idea.');
INSERT OR IGNORE INTO "CONFIG" VALUES('UMTS.Debug.Messages','1',0,0,'1=enabled, 0=disabled - Enable debug printout of RRC messages.');
INSERT OR IGNORE INTO "CONFIG" VALUES('UMTS.Debug.SIB','1',0,0,'1=enabled, 0=disabled - Enable debug printouts of SIB RRC message.');
INSERT OR IGNORE INTO "CONFIG" VALUES('UMTS.Downlink.ScramblingCode','469',0,0,'UMTS downlink scrambling code.  It is the same for all downlink channels.');
INSERT OR IGNORE INTO "CONFIG" VALUES('UMTS.Identity.CI','10',0,0,'Cell ID, 16 bits.  Should be unique.');
INSERT OR IGNORE INTO "CONFIG" VALUES('UMTS.Identity.LAC','132',0,0,'Location area code, 16 bits, values 0xFFxx are reserved.  For multi-NodeB networks, assign a unique LAC to each NodeB unit.  (That is not the normal procedure in conventional UMTS networks, but is the correct procedure in OpenBTS-UMTS networks.)');
INSERT OR IGNORE INTO "CONFIG" VALUES('UMTS.Identity.MCC','001',0,0,'Mobile country code; must be three.  Defined in ITU-T E.212. 001 for test networks.');
INSERT OR IGNORE INTO "CONFIG" VALUES('UMTS.Identity.MNC','01',0,0,'Mobile network code, two or three digits.  Assigned by your national regulator. 01 for test networks.');
INSERT OR IGNORE INTO "CONFIG" VALUES('UMTS.Identity.URAI','100',0,0,'UTRAN Registration Area Identity, 16 bits.');
INSERT OR IGNORE INTO "CONFIG" VALUES('UMTS.PCPICHUsageForChannelEst','1',0,0,'1=enabled, 0=disabled - Flag to indicate that UE should use PCPICH for channel estimation.');
INSERT OR IGNORE INTO "CONFIG" VALUES('UMTS.PICH.PICH-PowerOffset','-10',0,0,'PICH power offset in dB.');
INSERT OR IGNORE INTO "CONFIG" VALUES('UMTS.PRACH.DynamicPersistenceLevel','1',0,0,'Dynamic Persistence Level for PRACH channel.  Valid values unknown.');
INSERT OR IGNORE INTO "CONFIG" VALUES('UMTS.PRACH.SF','32',0,0,'Spreading Factor of PRACH.  Valid values are 32, 64, 128 and 256.');
INSERT OR IGNORE INTO "CONFIG" VALUES('UMTS.PRACH.ScramblingCode','0',0,0,'PRACH scrambling code for PRACH bursts.');
INSERT OR IGNORE INTO "CONFIG" VALUES('UMTS.PRACH.Signature','13',0,0,'Sequence used for PRACH accesses.');
INSERT OR IGNORE INTO "CONFIG" VALUES('UMTS.PRACH.Subchannel','1',0,0,'PRACH subchannel.');
INSERT OR IGNORE INTO "CONFIG" VALUES('UMTS.RLC.TransmissionBufferSize','1000000',0,0,'Buffer size in Bytes for RLC Transmission layer.');
INSERT OR IGNORE INTO "CONFIG" VALUES('UMTS.Radio.ARFCNs','1',1,0,'The number of ARFCNs to use.  The ARFCN set will be C0, C0+2, C0+4, etc.  Static.');
INSERT OR IGNORE INTO "CONFIG" VALUES('UMTS.Radio.Band','900',1,0,'The UMTS operating band.  Valid values are 850, 900, 1700, 1800, 1900 and 2100.  For most Range models, this value is dictated by the hardware and should not be changed.  Static.');
INSERT OR IGNORE INTO "CONFIG" VALUES('UMTS.Radio.C0','3050',1,0,'The UARFCN.  Range of valid values depend upon the selected operating band.  Static.');
INSERT OR IGNORE INTO "CONFIG" VALUES('UMTS.Radio.MaxExpectedDelaySpread','50',0,0,'Expected worst-case delay spread in symbol periods, roughly 3.7 us or 1.1 km per unit.');
INSERT OR IGNORE INTO "CONFIG" VALUES('UMTS.Radio.PowerManager.MaxAttenDB','10',0,0,'Maximum transmitter attenuation level, in dB wrt full scale on the D/A output.  This sets the minimum power output level in the output power control loop.');
INSERT OR IGNORE INTO "CONFIG" VALUES('UMTS.Radio.PowerManager.MinAttenDB','0',0,0,'Minimum transmitter attenuation level, in dB wrt full scale on the D/A output.  This sets the maximum power output level in the output power control loop.');
INSERT OR IGNORE INTO "CONFIG" VALUES('UMTS.Radio.PowerManager.NumSamples','10',0,0,'Number of samples averaged by the output power control loop.');
INSERT OR IGNORE INTO "CONFIG" VALUES('UMTS.Radio.PowerManager.Period','6000',0,0,'Power manager control loop master period, in milliseconds.');
INSERT OR IGNORE INTO "CONFIG" VALUES('UMTS.Radio.PowerManager.SamplePeriod','2000',0,0,'Sample period for the output power control loopm in milliseconds.');
INSERT OR IGNORE INTO "CONFIG" VALUES('UMTS.Radio.PowerManager.TargetT3122','5000',0,0,'Target value for T3122, the random access hold-off timer, for the power control loop.');
INSERT OR IGNORE INTO "CONFIG" VALUES('UMTS.Radio.RxGain','57',1,0,'Receiver gain setting in dB.  Ideal value is dictacted by the hardware.  This database parameter is static but the receiver gain can be modified in real time with the CLI rxgain command.  Static.');
INSERT OR IGNORE INTO "CONFIG" VALUES('UMTS.SCCPCH.SF','64',0,0,'Spreading Factor of SCCPCH.  Valid values are 4, 8, 16, 32, 64, 128 and 256.');
INSERT OR IGNORE INTO "CONFIG" VALUES('UMTS.SCCPCH.SpreadingCode','2',0,0,'Spreading code for SCCPCH bursts.');
INSERT OR IGNORE INTO "CONFIG" VALUES('UMTS.SRNC_ID','0',0,0,'RNC ID.');
INSERT OR IGNORE INTO "CONFIG" VALUES('UMTS.Timer.T3212','30',0,0,'Registration timer T3212 period in minutes.  Should be a factor of 6.  Set to 0 to disable periodic registration.  Should be smaller than SIP registration period.');
INSERT OR IGNORE INTO "CONFIG" VALUES('UMTS.Timers.Inactivity.Delete','300',0,0,'In seconds, period of inactivity before UE in Idle mode is purged from active list.');
INSERT OR IGNORE INTO "CONFIG" VALUES('UMTS.Timers.Inactivity.Release','180',0,0,'In seconds, period of inactivity before UE in CELL_PCH mode is released.  Not used.');
INSERT OR IGNORE INTO "CONFIG" VALUES('UMTS.Uplink.Puncturing.Limit','100',0,0,'Puncturing Limit of L1 rate-matcher for uplink.  Do not use.');
INSERT OR IGNORE INTO "CONFIG" VALUES('UMTS.Uplink.ScramblingCode','543',0,0,'Base index for DCH scrambling codes assigned to UEs.  Valid values are 0 to 2^31.');
INSERT OR IGNORE INTO "CONFIG" VALUES('UMTS.UseTurboCodes','1',0,0,'1=enabled, 0=disabled - Are turbocodes enabled.');
COMMIT;


